Repository read-with-me/reading-list, pull requests merged in 2024-09, with the labels that each got.

#3 fix: temp
  pull_request_template.md
Labels: ⚒️ 오탈자 수정

#4 ADD: 객체지향 사실과 오해 1장(협력하는 객체들의 공동체) 정리
  0_객체지향의_사실과_오해/2Jaeheon/01/README.md
Labels: 📚 기록

#5 [객체지향의 사실과 오해] 01. 협력하는 객체들의 공동체
  0_객체지향의_사실과_오해/songforthemute/01/README.md
Labels: 📚 기록

#7 [객체지향의 사실과 오해] 02. 이상한 나라의 객체
  0_객체지향의_사실과_오해/README.md
  0_객체지향의_사실과_오해/songforthemute/01/README.md
  0_객체지향의_사실과_오해/songforthemute/02/README.md
Labels: 📚 기록, ⚙️ 설정 수정

#6 [객체지향의 사실과 오해] 02. 이상한 나라의 객체
  0_객체지향의_사실과_오해/2Jaeheon/02/README.md
Labels: 📚 기록
